# Generated by Django 5.2.17 on 2026-09-30 17:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('grid', 'Utility Grid'), ('solar', 'Solar PV'), ('hydro', 'Hydropower'), ('wind', 'Wind Energy'), ('biomass', 'Biomass / Other')], db_index=True, max_length=20)),
                ('is_renewable', models.BooleanField(db_index=True, default=False, help_text='True for zero-direct-emission renewable sources')),
                ('emission_factor', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Grid or source emission factor in kg CO2 per kWh', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional facility code, e.g., BLK-A, PLANT-01', max_length=50)),
                ('facility_type', models.CharField(blank=True, default='Commercial', help_text='e.g. Office, Manufacturing, Data Centre, Warehouse', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Physical location or zone on campus', max_length=255)),
                ('floor_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Total covered rooftop or floor area in sq. ft.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this facility is actively monitored')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('consumption_kwh', models.DecimalField(decimal_places=2, help_text='Total billable consumption in kWh', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total payable invoice amount in ₹', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('energy_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Variable energy consumption charge in ₹', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('demand_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed sanctioned peak demand charge in ₹', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxes_and_duties', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Electricity duty and municipal surcharges in ₹', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tariff_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Blended tariff rate (₹/kWh)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Identifies demonstration sample invoices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility associated with this invoice (leave blank for campus-wide bill)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to='energy.facility')),
            ],
            options={
                'ordering': ['-billing_period_end'],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reading_value', models.DecimalField(decimal_places=3, help_text='Energy quantity in the specified unit (typically kWh)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('demand_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Peak instantaneous electric demand in kW', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Flag explicitly distinguishing demonstrative sample data from live readings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('energy_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='energy.energysource')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='energy.facility')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['facility', 'timestamp'], name='energy_ener_facilit_d2e638_idx'), models.Index(fields=['energy_source', 'timestamp'], name='energy_ener_energy__34079a_idx'), models.Index(fields=['timestamp', 'is_demo'], name='energy_ener_timesta_7a2973_idx')],
            },
        ),
    ]
