# Generated by Django 5.2.17 on 2026-10-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyreading',
            name='reading_type',
            field=models.CharField(choices=[('consumption', 'Consumption'), ('generation', 'Generation')], db_index=True, default='consumption', help_text='Designates whether the reading measures energy consumption or generation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='energyreading',
            index=models.Index(fields=['reading_type', 'timestamp'], name='energy_ener_reading_a2256b_idx'),
        ),
    ]
