# Generated by Django 5.2.17 on 2026-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_energyreading_reading_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyreading',
            name='data_source',
            field=models.CharField(blank=True, db_index=True, default='synthetic', help_text="Original dataset source, e.g., 'kaggle:household-power', 'kaggle:solar-generation', 'synthetic'", max_length=100),
        ),
        migrations.AddIndex(
            model_name='energyreading',
            index=models.Index(fields=['data_source', 'timestamp'], name='energy_ener_data_so_e32afa_idx'),
        ),
    ]
