/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnergyMonitoringRouteImport } from './routes/energy-monitoring'
import { Route as SmartGridRouteImport } from './routes/smart-grid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyMonitoringRoute = EnergyMonitoringRouteImport.update({
  id: '/energy-monitoring',
  path: '/energy-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartGridRoute = SmartGridRouteImport.update({
  id: '/smart-grid',
  path: '/smart-grid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/energy-monitoring': typeof EnergyMonitoringRoute
  '/smart-grid': typeof SmartGridRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/energy-monitoring': typeof EnergyMonitoringRoute
  '/smart-grid': typeof SmartGridRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/energy-monitoring': typeof EnergyMonitoringRoute
  '/smart-grid': typeof SmartGridRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/energy-monitoring' | '/smart-grid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/energy-monitoring' | '/smart-grid'
  id: '__root__' | '/' | '/energy-monitoring' | '/smart-grid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnergyMonitoringRoute: typeof EnergyMonitoringRoute
  SmartGridRoute: typeof SmartGridRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-monitoring': {
      id: '/energy-monitoring'
      path: '/energy-monitoring'
      fullPath: '/energy-monitoring'
      preLoaderRoute: typeof EnergyMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-grid': {
      id: '/smart-grid'
      path: '/smart-grid'
      fullPath: '/smart-grid'
      preLoaderRoute: typeof SmartGridRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnergyMonitoringRoute: EnergyMonitoringRoute,
  SmartGridRoute: SmartGridRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
